### PR TITLE
[feat] Adds option to load demo xAPI data

### PR DESCRIPTION
**Pull request by pomegranited**
Ensures the ports exposed by Clickhouse (for client and HTTP) are configurable, and accessible as variables in Tutor plugins.
Adds option to load xapi demo data into Clickhouse on init.

**Dependencies**

These need to be merged first, and a `0.1` tag added to `xapi-db-api`.

* https://github.com/bmtcril/xapi-db-load/pull/1
* https://github.com/openedx/xapi-db-load/pull/5

**Related discussions**

* Part of implementing https://github.com/openedx/openedx-oars/issues/30

**Testing instructions**

1. Install this branch to your tutor virtualenv.
2. Run `tutor config save` and `tutor local restart clickhouse` to ensure these config changes are valid.
3. To ensure the demo data is disabled by default: Run `tutor local do init --limit clickhouse`, and note that no demo tables are created on the `xapi` database.
4. To test the demo data: Run `tutor config save -s CLICKHOUSE_LOAD_DEMO_DATA=xapi && tutor local do init --limit clickhouse`, and note that a `xapi_events_all` table is added to the `xapi` database.

### CODE REVIEW

**Comment by pomegranited** [comment]
Hi @bmtcril -- just a little one so I can use `{{ CLICKHOUSE_HTTP_PORT }}` in my tutor plugin scripts.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by pomegranited** [comment]
Thank you @bmtcril !

And yep, I'm happy to contribute to this openedx repo under my CLA.

**Comment by pomegranited** [comment]
Hi @bmtcril ! Dependency updated, so this is ready for your review.

**Review by bmtcril — APPROVED** [review]
👍

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-clickhouse&entry.867055334=https://github.com/openedx/tutor-contrib-clickhouse/pull/1&entry.1484655318=https://github.com/pomegranited&entry.752974735=2023-01-25+10:46&entry.1917517419=2023-02-13+23:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
